//! Map the raw composite onto a percentile of real reasoning traces.
//!
//! The raw composite is crushed into the top of its range: on the 2,517-trace
//! reference corpus it runs 66.6..100 with a median of 85.3, and **99.9% of real
//! traces score above 70**. A user filtering at `--min-score 70` therefore keeps
//! essentially everything, and the number on the scorecard means nothing (the
//! gallery's "never answers" trace showed 82.9, in green). That is issue #30.
//!
//! So the reported `quality_score` is the trace's **percentile against a
//! reference distribution of real traces** — "better than N% of real reasoning
//! traces" — while the underlying composite is preserved as `raw_score`. The
//! ranking is unchanged (the mapping is monotone); only the scale moves.
//!
//! The reference distribution lives in [`table`], generated by
//! `scripts/fit_calibration.py`. It is fitted against the DEFAULT scoring
//! weights — change the weights without refitting and the percentiles lie.

mod table;

use table::REFERENCE_KNOTS;

/// Raw composite -> percentile (0..=100) against the reference corpus.
///
/// Monotone non-decreasing, so it never reorders traces: filtering and ranking
/// behave identically, but the number is now interpretable and selective.
/// Scores below/above the reference range clamp to 0/100.
pub fn calibrate(raw: f32) -> f32 {
    let last = REFERENCE_KNOTS.len() - 1; // 100
    if !raw.is_finite() {
        return 0.0;
    }
    if raw <= REFERENCE_KNOTS[0] {
        return 0.0;
    }
    if raw >= REFERENCE_KNOTS[last] {
        return 100.0;
    }

    // Find the first knot >= raw. The table is non-decreasing (the generator
    // asserts it), so partition_point gives us the upper neighbour directly.
    let hi = REFERENCE_KNOTS.partition_point(|&k| k < raw);
    let lo = hi - 1;

    let span = REFERENCE_KNOTS[hi] - REFERENCE_KNOTS[lo];
    // Duplicate knots (a flat region of the reference distribution) would divide
    // by zero; land on the lower percentile instead.
    if span <= f32::EPSILON {
        return lo as f32;
    }

    let frac = (raw - REFERENCE_KNOTS[lo]) / span;
    (lo as f32 + frac).clamp(0.0, 100.0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_monotone() {
        // A non-monotone table would silently corrupt every score via the
        // binary search. This is the load-bearing invariant.
        for w in REFERENCE_KNOTS.windows(2) {
            assert!(w[1] >= w[0], "knots not sorted: {} then {}", w[0], w[1]);
        }
    }

    #[test]
    fn endpoints_clamp() {
        assert_eq!(calibrate(0.0), 0.0);
        assert_eq!(calibrate(-5.0), 0.0);
        assert_eq!(calibrate(100.0), 100.0);
        assert_eq!(calibrate(150.0), 100.0);
        assert_eq!(calibrate(f32::NAN), 0.0);
    }

    #[test]
    fn knots_map_to_their_own_percentile() {
        for (p, &raw) in REFERENCE_KNOTS.iter().enumerate() {
            let got = calibrate(raw);
            // Flat regions map to the first percentile that reaches the value,
            // so only assert we never exceed the knot's own percentile.
            assert!(
                got <= p as f32 + 0.01,
                "p{p} raw={raw} calibrated to {got}, above its own percentile"
            );
        }
    }

    #[test]
    fn is_monotone_over_the_whole_range() {
        // Ranking must be preserved — this is what makes the rescale safe.
        let mut prev = -1.0;
        let mut raw = 60.0;
        while raw <= 101.0 {
            let got = calibrate(raw);
            assert!(got >= prev, "calibrate({raw}) = {got} < previous {prev}");
            prev = got;
            raw += 0.05;
        }
    }

    #[test]
    fn median_of_reference_corpus_lands_near_50() {
        // p50 of the reference corpus is raw 85.29 (see docs/CALIBRATION.md).
        let got = calibrate(85.29);
        assert!(
            (got - 50.0).abs() < 2.0,
            "the corpus median should sit near the 50th percentile, got {got}"
        );
    }

    #[test]
    fn the_rambling_trace_is_no_longer_green() {
        // The whole point of #30: the gallery's "grinds trial division for 700
        // words and never answers" trace scored raw 82.9 and rendered GREEN.
        let got = calibrate(82.9);
        assert!(
            got < 50.0,
            "r1-rambling (raw 82.9) should fall below the median trace, got {got}"
        );
    }

    #[test]
    fn the_old_default_threshold_is_now_selective() {
        // `--min-score 70` used to keep 99.9% of real traces. On the calibrated
        // scale it means "top 30%" by construction: the raw value at p70.
        let raw_at_p70 = REFERENCE_KNOTS[70];
        assert!((calibrate(raw_at_p70) - 70.0).abs() < 1.0);
    }
}
