// GENERATED by scripts/fit_calibration.py — do not edit by hand.
//
// Reference distribution of the RAW composite over real reasoning traces.
// Fitted on n=2517 traces: limo_scored_fixed.jsonl (817), s1k_scored_fixed.jsonl (1000), medical_scored_fixed.jsonl (700).
//
// KNOTS[p] is the raw composite at the p-th percentile of that corpus, so
// mapping a raw score back through this table yields its percentile. See
// docs/CALIBRATION.md and issue #30 for why the raw scale needed this.
//
// Fitted against the DEFAULT scoring weights. If the weights change, refit:
// the percentiles silently lie otherwise.
pub(crate) const REFERENCE_KNOTS: [f32; 101] = [
    66.6235, 74.0566, 75.7497, 76.3105, 76.6006, 76.8453, 76.9744, 77.1654, 77.3839, 77.6312,
    77.9807, 78.3860, 78.6805, 78.8986, 79.0783, 79.2093, 79.2921, 79.4050, 79.4960, 79.5972,
    79.7284, 79.8370, 79.9562, 80.1060, 80.2071, 80.3829, 80.5217, 80.6379, 80.7297, 80.8386,
    80.9880, 81.1296, 81.2621, 81.4175, 81.6070, 81.7892, 81.9554, 82.1921, 82.3991, 82.6184,
    82.8224, 83.1134, 83.4359, 83.6293, 83.7576, 84.0239, 84.2719, 84.5790, 84.7502, 84.9764,
    85.2853, 85.5517, 85.7632, 86.0394, 86.2078, 86.3958, 86.6129, 86.9047, 87.1741, 87.4144,
    87.6950, 87.9237, 88.1523, 88.3993, 88.6488, 88.8356, 89.0020, 89.1889, 89.3671, 89.5326,
    89.7031, 89.8920, 90.1087, 90.2889, 90.5085, 90.7104, 90.9342, 91.1236, 91.3683, 91.5851,
    91.8492, 92.1439, 92.3254, 92.5506, 92.8542, 93.0992, 93.3744, 93.5987, 93.8139, 94.0326,
    94.3278, 94.6969, 95.0943, 95.3595, 95.6612, 95.9924, 96.3971, 96.7610, 97.2192, 97.8000,
    100.0000,
];
