#!/usr/bin/env python3
"""Fit the score-calibration curve and emit the Rust knot table.

WHY THIS EXISTS (issue #30): the raw composite is crushed into the top of the
0-100 range — on the 2,517-trace reference corpus it runs 66.6..100 with median
85.3, and 99.9% of real traces land above 70. So `filter --min-score 70` keeps
essentially everything and the number a user sees is meaningless.

The fix is to report a trace's *percentile against a reference distribution of
real reasoning traces* instead of the raw composite. Then `quality_score = 70`
means "better than 70% of real traces", which is both interpretable and
actually selective.

This script fits that mapping and prints a Rust `const` table for
`crates/reasonmetrics-core/src/calibration.rs`. The curve is data, not a magic
number: it is regenerated by running this over the reference corpora.

    reasonmetrics score -i limo_traces.jsonl    -o limo_scored.jsonl
    reasonmetrics score -i s1k_traces.jsonl     -o s1k_scored.jsonl
    reasonmetrics score -i medical_traces.jsonl -o medical_scored.jsonl
    python scripts/fit_calibration.py limo_scored.jsonl s1k_scored.jsonl \
        medical_scored.jsonl > crates/reasonmetrics-core/src/calibration_table.rs

IMPORTANT: the curve is fitted against the DEFAULT scoring weights. Change the
weights and the raw composite's distribution moves, so the curve must be refit
or the percentiles silently lie. That is why both live in the maintainer-only
zone (see CONTRIBUTING.md ownership zones).

Reads `raw_score` if present (already-calibrated output), else `quality_score`,
so it is safe to re-run against a corpus scored by a calibrated binary.

No third-party dependencies.
"""
from __future__ import annotations

import argparse
import json
import sys

KNOTS = 101  # p0..p100 inclusive


def load_composites(paths: list[str]) -> tuple[list[float], dict[str, int]]:
    """Pull the RAW composite from each scored trace."""
    values: list[float] = []
    per_file: dict[str, int] = {}
    for path in paths:
        n = 0
        with open(path, encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                r = json.loads(line)
                # A corpus scored by a calibrated binary carries the raw composite
                # in `raw_score`; an older one only has `quality_score`.
                v = r.get("raw_score", r.get("quality_score"))
                if v is None:
                    continue
                values.append(float(v))
                n += 1
        if n == 0:
            sys.exit(f"{path}: no scored rows found")
        per_file[path] = n
    return values, per_file


def quantile(sorted_vals: list[float], q: float) -> float:
    """Linear-interpolated quantile, q in [0, 1]."""
    if not sorted_vals:
        raise ValueError("empty")
    if q <= 0:
        return sorted_vals[0]
    if q >= 1:
        return sorted_vals[-1]
    pos = q * (len(sorted_vals) - 1)
    lo = int(pos)
    hi = min(lo + 1, len(sorted_vals) - 1)
    frac = pos - lo
    return sorted_vals[lo] * (1 - frac) + sorted_vals[hi] * frac


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("scored", nargs="+", help="scored JSONL reference corpora")
    args = ap.parse_args()

    values, per_file = load_composites(args.scored)
    values.sort()
    n = len(values)

    knots = [quantile(values, p / (KNOTS - 1)) for p in range(KNOTS)]

    # The table must be non-decreasing for the binary search in calibrate() to be
    # correct. Interpolated quantiles of sorted data always are, but assert it
    # rather than trust it — a silently unsorted table would corrupt every score.
    for i in range(1, KNOTS):
        if knots[i] < knots[i - 1]:
            sys.exit(f"BUG: knot table is not monotone at p{i}")

    corpora = ", ".join(f"{p.split('/')[-1]} ({c})" for p, c in per_file.items())

    print("// GENERATED by scripts/fit_calibration.py — do not edit by hand.")
    print("//")
    print("// Reference distribution of the RAW composite over real reasoning traces.")
    print(f"// Fitted on n={n} traces: {corpora}.")
    print("//")
    print("// KNOTS[p] is the raw composite at the p-th percentile of that corpus, so")
    print("// mapping a raw score back through this table yields its percentile. See")
    print("// docs/CALIBRATION.md and issue #30 for why the raw scale needed this.")
    print("//")
    print("// Fitted against the DEFAULT scoring weights. If the weights change, refit:")
    print("// the percentiles silently lie otherwise.")
    # 10 per row is what rustfmt settles on for this width — emit it directly so
    # the generated file passes `cargo fmt --check` without a manual reformat.
    print(f"pub(crate) const REFERENCE_KNOTS: [f32; {KNOTS}] = [")
    for i in range(0, KNOTS, 10):
        row = ", ".join(f"{k:.4f}" for k in knots[i : i + 10])
        print(f"    {row},")
    print("];")

    # Diagnostics to stderr so stdout stays a clean Rust file.
    print(f"\nfitted on n={n} from {len(per_file)} corpora", file=sys.stderr)
    for p, c in per_file.items():
        print(f"  {p}: {c}", file=sys.stderr)
    print("percentile -> raw composite:", file=sys.stderr)
    for p in (0, 1, 5, 10, 25, 50, 75, 90, 95, 99, 100):
        print(f"  p{p:<3} = {knots[p]:.2f}", file=sys.stderr)
    frac_above_70 = sum(1 for v in values if v >= 70.0) / n
    print(f"\nraw >= 70 today: {frac_above_70:.1%} of the corpus "
          f"(this is the #30 defect)", file=sys.stderr)


if __name__ == "__main__":
    main()
